/* lighthouse.yml — © Hardonia. MIT. */
name: lighthouse
on:
  workflow_dispatch: {}
  push:
    tags: ['v*.*.*']
jobs:
  lh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Serve locally & run lhci
        run: |
          npm i --prefix packages/shopify/epr-bluebox-app || true
          nohup node packages/shopify/epr-bluebox-app/server.js >/dev/null 2>&1 &
          sleep 2
          npx -y @lhci/cli autorun --collect.url=http://localhost:3000/reports.html || true
      - uses: actions/upload-artifact@v4
        with:
          name: lighthouse
          path: .lighthouseci
