name: release
<<<<<<< HEAD
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Package ZIP
        run: |
          bash tools/package.sh "${GITHUB_REF_NAME}"
          echo "ZIP_PATH=$(ls dist/*.zip)" >> $GITHUB_ENV
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ZIP_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
=======
on: {push: {tags: ['v*.*.*']}}
>>>>>>> 95bdcb5 (feat: Suite A v3.4.4 sell-ready (docs+ngrok+slack))
